const FLAGS: Record<string, string> = {
  // España y entorno
  'España': '🇪🇸', 'Spain': '🇪🇸',
  'Francia': '🇫🇷', 'France': '🇫🇷',
  'Alemania': '🇩🇪', 'Germany': '🇩🇪',
  'Inglaterra': '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Portugal': '🇵🇹',
  'Países Bajos': '🇳🇱', 'Holanda': '🇳🇱', 'Netherlands': '🇳🇱',
  'Bélgica': '🇧🇪', 'Belgium': '🇧🇪',
  'Croacia': '🇭🇷', 'Croatia': '🇭🇷',
  'Italia': '🇮🇹', 'Italy': '🇮🇹',
  'Suiza': '🇨🇭', 'Switzerland': '🇨🇭',
  'Dinamarca': '🇩🇰', 'Denmark': '🇩🇰',
  'Polonia': '🇵🇱', 'Poland': '🇵🇱',
  'Austria': '🇦🇹',
  'Escocia': '🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Turquía': '🇹🇷', 'Turkey': '🇹🇷', 'Türkiye': '🇹🇷',
  'Eslovaquia': '🇸🇰', 'Slovakia': '🇸🇰',
  'Rumanía': '🇷🇴', 'Romania': '🇷🇴',
  'Eslovenia': '🇸🇮', 'Slovenia': '🇸🇮',
  'Georgia': '🇬🇪',
  'Serbia': '🇷🇸',
  'Albania': '🇦🇱',
  'Hungría': '🇭🇺', 'Hungary': '🇭🇺',
  'Ucrania': '🇺🇦', 'Ukraine': '🇺🇦',
  'Gales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿', 'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  'Noruega': '🇳🇴', 'Norway': '🇳🇴',
  'Suecia': '🇸🇪', 'Sweden': '🇸🇪',
  'Finlandia': '🇫🇮', 'Finland': '🇫🇮',
  'República Checa': '🇨🇿', 'Czech Republic': '🇨🇿', 'Czechia': '🇨🇿',
  'Grecia': '🇬🇷', 'Greece': '🇬🇷',
  // América
  'Argentina': '🇦🇷',
  'Brasil': '🇧🇷', 'Brazil': '🇧🇷',
  'Uruguay': '🇺🇾',
  'Colombia': '🇨🇴',
  'Ecuador': '🇪🇨',
  'México': '🇲🇽', 'Mexico': '🇲🇽',
  'Estados Unidos': '🇺🇸', 'USA': '🇺🇸', 'United States': '🇺🇸',
  'Canadá': '🇨🇦', 'Canada': '🇨🇦',
  'Chile': '🇨🇱',
  'Paraguay': '🇵🇾',
  'Perú': '🇵🇪', 'Peru': '🇵🇪',
  'Bolivia': '🇧🇴',
  'Venezuela': '🇻🇪',
  'Honduras': '🇭🇳',
  'Costa Rica': '🇨🇷',
  'Panamá': '🇵🇦', 'Panama': '🇵🇦',
  'Jamaica': '🇯🇲',
  'Guatemala': '🇬🇹',
  'El Salvador': '🇸🇻',
  'Trinidad y Tobago': '🇹🇹', 'Trinidad and Tobago': '🇹🇹',
  'Cuba': '🇨🇺',
  // África
  'Marruecos': '🇲🇦', 'Morocco': '🇲🇦',
  'Senegal': '🇸🇳',
  'Nigeria': '🇳🇬',
  'Costa de Marfil': '🇨🇮', 'Ivory Coast': '🇨🇮', "Côte d'Ivoire": '🇨🇮',
  'Sudáfrica': '🇿🇦', 'South Africa': '🇿🇦',
  'Ghana': '🇬🇭',
  'Argelia': '🇩🇿', 'Algeria': '🇩🇿',
  'Túnez': '🇹🇳', 'Tunisia': '🇹🇳',
  'Camerún': '🇨🇲', 'Cameroon': '🇨🇲',
  'Egipto': '🇪🇬', 'Egypt': '🇪🇬',
  'Malí': '🇲🇱', 'Mali': '🇲🇱',
  'Mozambique': '🇲🇿',
  'Angola': '🇦🇴',
  'Uganda': '🇺🇬',
  'Tanzania': '🇹🇿',
  'Zambia': '🇿🇲',
  'Guinea': '🇬🇳',
  'República Democrática del Congo': '🇨🇩', 'DR Congo': '🇨🇩', 'Congo DR': '🇨🇩',
  'Etiopía': '🇪🇹', 'Ethiopia': '🇪🇹',
  'Kenia': '🇰🇪', 'Kenya': '🇰🇪',
  'Libia': '🇱🇾', 'Libya': '🇱🇾',
  'Gabón': '🇬🇦', 'Gabon': '🇬🇦',
  'Burkina Faso': '🇧🇫',
  // Asia
  'Japón': '🇯🇵', 'Japan': '🇯🇵',
  'Corea del Sur': '🇰🇷', 'South Korea': '🇰🇷',
  'Irán': '🇮🇷', 'Iran': '🇮🇷',
  'Australia': '🇦🇺',
  'Arabia Saudí': '🇸🇦', 'Saudi Arabia': '🇸🇦',
  'Catar': '🇶🇦', 'Qatar': '🇶🇦',
  'Irak': '🇮🇶', 'Iraq': '🇮🇶',
  'Jordania': '🇯🇴', 'Jordan': '🇯🇴',
  'Uzbekistán': '🇺🇿', 'Uzbekistan': '🇺🇿',
  'Indonesia': '🇮🇩',
  'Emiratos Árabes': '🇦🇪', 'UAE': '🇦🇪', 'United Arab Emirates': '🇦🇪',
  'Omán': '🇴🇲', 'Oman': '🇴🇲',
  'Bahréin': '🇧🇭', 'Bahrain': '🇧🇭',
  'China': '🇨🇳',
  'India': '🇮🇳',
  'Corea del Norte': '🇰🇵', 'North Korea': '🇰🇵',
  'Kuwait': '🇰🇼',
  'Siria': '🇸🇾', 'Syria': '🇸🇾',
  'Palestina': '🇵🇸', 'Palestine': '🇵🇸',
  'Tailandia': '🇹🇭', 'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'Malasia': '🇲🇾', 'Malaysia': '🇲🇾',
  'Filipinas': '🇵🇭', 'Philippines': '🇵🇭',
  // Oceanía
  'Nueva Zelanda': '🇳🇿', 'New Zealand': '🇳🇿',
  'Fiji': '🇫🇯',
  'Papua Nueva Guinea': '🇵🇬', 'Papua New Guinea': '🇵🇬',
}

export function getFlag(teamName: string | null | undefined): string {
  if (!teamName) return ''
  if (FLAGS[teamName]) return FLAGS[teamName]
  // Búsqueda sin distinguir mayúsculas
  const lower = teamName.toLowerCase()
  const match = Object.entries(FLAGS).find(([k]) => k.toLowerCase() === lower)
  return match ? match[1] : ''
}
